### ISSUE TITLE
Compile Error 'MyHandleNMEA2000Msg' was not declared in this scope

### ISSUE THREAD

**Issue by SV-Krishna** [AK-Homberger/NMEA2000-SignalK-Gateway#1]
When attempting to build this project I get the following error in PlatformIO

Compiling .pio\build\dfrobot_firebeetle2_esp32e\lib2e6\NMEA2000-master\N2kGroupFunction.cpp.o
Compiling .pio\build\dfrobot_firebeetle2_esp32e\lib2e6\NMEA2000-master\N2kGroupFunctionDefaultHandlers.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:108:26: error: 'MyHandleNMEA2000Msg' was not declared in this scope
   NMEA2000.SetMsgHandler(MyHandleNMEA2000Msg);
                          ^~~~~~~~~~~~~~~~~~~
*** [.pio\build\dfrobot_firebeetle2_esp32e\src\main.cpp.o] Error 1
================================================= [FAILED] Took 11.02 seconds =================================================
 *  The terminal process "C:\Users\Antony Slack\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by AK-Homberger** [comment]
Hi,

with Arduino IDE 1.8.19 and Espressif ESP32 board version 1.0.6 it compiles without errors. That's the combination I used while creating this repository.

Regards,
Andreas

**Comment by AK-Homberger** [comment]
Depending on the compiler you are using, it might be necessry to re-order the functions or to use function prototypes to ensure functions ar decleard before used. The Arduino IDE does not care about this.

**Comment by SV-Krishna** [comment]
> Hi,
> 
> with Arduino IDE 1.8.19 and Espressif ESP32 board version 1.0.6 it compiles without errors. That's the combination I used while creating this repository.
> 
> Regards, Andreas

Thanks for getting back to me Andreas. 

Based on your note these are the changes I have made:

- I had been using platformIO as the compiler. I have now switched to Arduino 1.8.19.
- I had been using a firebeetle ESP32-E V1.0 Board and have changed this now to ESP32 Dev Board. I've not been able to specify Espressif ESP32 board version 1.0.6 specifically in the Aduino Sketch Board Manager

To recap:

- I am trying to compile this sketch "Read PGNs from NMEA2000-Bus and send as Yacht Devices format to SignalK server (UDP) // Version 0.2, 12.02.2021, AK-Homberger"
- I have installed the two libraries NMEA2000 and NMEA2000_esp32 (via [ZIP-File] required in the readme file following the instructions in section - 2. WLAN Gateway (all PGNs)

Issues:

When I run the compiler in Arduino IDE 1.8.19 I receive the errors in the attached file
[Compile Errors Arduino 1.8.19 Windows 10 Board ESP32 Dev Module.txt](https://github.com/AK-Homberger/NMEA2000-SignalK-Gateway/files/13674976/Compile.Errors.Arduino.1.8.19.Windows.10.Board.ESP32.Dev.Module.txt)

**Comment by SV-Krishna** [comment]
Hi Andreas, I have resolved the problem.

Downloading Arduino 1.8.19. In File, Preferences, additional board manager URLs - the default URL needs to be changed to https://dl.espressif.com/dl/package_esp32_index.json. O

This URL is no longer supported by espressif so isn't included in the default installation of 1.8.19 any more. 

Once the URL is added, going to Board Manager you can then find ESP32 v1.0.6 - which I couldn't do before. 

Once thats installed I then selected the ESP32 Dev Board, added the libraries and your sketch and it all compiled.
